version: "3.8"
services:

  postgres:
    image: postgres:14.1-alpine
    cpus: 0.5
    mem_limit: "250M"
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  #    volumes:
#      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  node:
    build: whois_server/
    image: airsunday/node-app
    cpus: 0.5
    mem_limit: "250M"
    env_file:
      - "./whois_server/.env"
    ports:
      - 8080:8080
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=WhoisDataBase
      - DATABASE_HOST=postgres # NAME OF THE SERVICE
    depends_on:
      - postgres
  vue:
    build: whois_client/
    image: airsunday/vue-app
    cpus: 0.5
    mem_limit: "250M"
    ports:
      - 80:8080
    depends_on:
        - node

volumes:
  postgres:
    driver: local
#    external: true