version: "3.8"
services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=WhoisDataBase
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  node:
    build: whois_server/
    image: airsunday/node-app
    env_file:
      - "./whois_server/.env"
    ports:
      - 8080:8080
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=WhoisDataBase
      - DATABASE_HOST=postgres # NAME OF THE SERVICE
    depends_on:
      - postgres
  vue:
    build: whois_client/
    image: airsunday/vue-app
    ports:
      - 80:8080
      - 443:443
    depends_on:
        - node
#
#volumes:
#  postgres:
#    driver: local
##    external: true
