version: "3.8"
services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=WhoisDataBase
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  node:
    build: whois_server/
    image: airsunday/node-app
    ports:
      - 8080:8080
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=WhoisDataBase
      - DATABASE_HOST=postgres # NAME OF THE SERVICE
      - SESSION_SECRET=VerySecret
      - EMAIL_PASSWORD=Freestyle_92
      - EMAIL_USER=AirSunday@yandex.ru
    depends_on:
      - postgres
  vue:
    build: whois_client/
    image: airsunday/vue-app
    ports:
      - 80:8080
      - 443:443
    depends_on:
      - node

volumes:
  postgres:
    driver: local
#    external: true
